### ISSUE TITLE
Support for t5uid1 (CR10S Pro) screen

### ISSUE THREAD

**Issue by marcinbauer-ohf** [Klipper3d/klipper#4625] opened 2021-08-27 19:59 UTC
Is there chance for Klipper to work with t5uid1 screen that is for instance in the CR10S Pro? I know there is apparently a version of Klipper with this support but its custom https://github.com/Desuuuu/DGUS-reloaded-Klipper and I haven't have success in running it.

**Comment by VIXIVIXIV** [comment] 2021-08-29 01:09
I can confirm the T5UID1 variant of Klipper works (it's what I run), you just need to follow the instructions that Desuuuu provides.

**Comment by marcinbauer85** [comment] 2021-08-29 09:05
It probably does, but could this be merged to the official repo since Desuuuu's has just this one change? I'll be locked to his releases, and not the official repo of Klipper.

**Comment by VIXIVIXIV** [comment] 2021-08-30 13:14
I agree it'd be nice, but so far I've had zero issues with forking from his and setting a github action to auto sync daily. Until it's made official, that's probably your best option

**Closed as completed** 2021-09-01 12:02 UTC
Labels: not on github
