### ISSUE TITLE
klipper compile  error for  uno328p

### ISSUE THREAD

**Issue by bihailantian655** [Klipper3d/klipper#5124] opened 2022-01-08 13:33 UTC
/usr/lib/gcc/avr/5.4.0/../../../avr/bin/ld: address 0x800a2e of out/klipper.elf section `.data' is not within region `data'
/usr/lib/gcc/avr/5.4.0/../../../avr/bin/ld: out/klipper.elf section `.data' will not fit in region `text'
/usr/lib/gcc/avr/5.4.0/../../../avr/bin/ld: address 0x800b98 of out/klipper.elf section `.bss' is not within region `data'
/usr/lib/gcc/avr/5.4.0/../../../avr/bin/ld: address 0x800a2e of out/klipper.elf section `.data' is not within region `data'
/usr/lib/gcc/avr/5.4.0/../../../avr/bin/ld: address 0x800b98 of out/klipper.elf section `.bss' is not within region `data'

the  compile  bin file is  too large

**Comment by Sineos** [comment] 2022-01-08 14:07
Duplicate of https://github.com/Klipper3d/klipper/issues/4938

**Closed by Sineos** 2022-01-08 14:07 UTC

**Comment by bihailantian655** [comment] 2022-01-08 14:10
so&nbsp; what is the solution ,or klipper will&nbsp; nerver support&nbsp; 328p ?


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Klipper3d/klipper"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月8日(星期六) 晚上10:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Klipper3d/klipper] klipper compile  error for  uno328p (Issue #5124)





 
Closed #5124.

**Comment by bihailantian655** [comment] 2022-01-08 14:16
> Duplicate of #4938

what is the solution ,or klipper will  nerver support 328p ?

**Comment by Sineos** [comment] 2022-01-08 14:42
This seems to be not a Klipper issue but an issue of the toolchain that is delivered with newer Linux distributions. So far no developer has analyzed this more deeply

IMHO the need is relatively low, since these old, low-end, 8bit boards are a dying breed anyway.

**Comment by bihailantian655** [comment] 2022-01-08 14:43
ok thanks&nbsp; ，




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月8日(星期六) 晚上10:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Klipper3d/klipper] klipper compile  error for  uno328p (Issue #5124)





 
This seems to be not a Klipper issue but an issue of the toolchain that is delivered with newer Linux distributions. So far no developer has analyzed this more deeply
 
IMHO the need is relatively low, since these old, low-end, 8bit boards are a dying breed anyway.
 
&mdash;

**Comment by mhier** [comment] 2022-02-08 20:42
I just ran into the same issue (wanted to test something with an Arduino Nano board instead of my printer). I got it to compile using this gcc 11 build for AVR:
https://blog.zakkemble.net/avr-gcc-builds/

Hence it is indeed a problem with the typically out-dated AVR toolchain. By default, Ubuntu comes with 5.4.0.

**Comment by moelski** [comment] 2022-03-04 19:13
Hi !
Just have written some documentation how to compile the whole AVR-GCC Toolchain on the Raspberry Pi for usage with klipper. Just did a test with an mega32u4 which didn´t work before. Now it compiles like a charme :-) 
So if anyone needs the doc ... let me know. But it took a long time to do it on a RPi ... ~6h at all for compiling the toolchain ... 
Dominik

**Comment by orobardet** [comment] 2022-04-09 21:27
@moelski I'm interested in your doc please, it may save me some time to figure out by myself how to build a fresh version of gcc-avr. Thanks!

**Comment by moelski** [comment] 2022-04-10 06:57
Hi !
Attached is my document ... It´s written in german but since it has only a few comments it should be possible to use it with deepl.com :-) Most of the text is console syntax ... 
If you encounter any problems feel free to give me a note ...
[avr-gcc_bullseye.pdf](https://github.com/Klipper3d/klipper/files/8458451/avr-gcc_bullseye.pdf)

**Comment by orobardet** [comment] 2022-04-10 11:10
> Hi ! Attached is my document ... It´s written in german but since it has only a few comments it should be possible to use it with deepl.com :-) Most of the text is console syntax ... If you encounter any problems feel free to give me a note ... [avr-gcc_bullseye.pdf](https://github.com/Klipper3d/klipper/files/8458451/avr-gcc_bullseye.pdf)

Thanks, i'll give it a try!
For those wondering, I also found an easier workaround, by reverting back the AVR package to buster (but that will only work as long as the buster archive package remains available for RaspiOS).  See https://github.com/Klipper3d/klipper/issues/4938#issuecomment-1094246978
