### ISSUE TITLE
Ender 3 pro 8 bit board V1.1.4

### ISSUE THREAD

**Issue by Andriuzzs** [Klipper3d/klipper#5034] opened 2021-12-17 20:06 UTC
Hi all. what config use Ender 3 Pro with bltouch and  how about software update to board 1.1.4 with usb isp

**Comment by Sineos** [comment] 2021-12-30 18:01
Duplicate of https://klipper.discourse.group/t/ender-3-pro-v1-1-4-main-board/1581/4

**Closed by Sineos** 2021-12-30 18:01 UTC
